name: Convert Draw.io Files

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Draw.io and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/jgraph/drawio-desktop/releases/download/v26.2.2/drawio-amd64-26.2.2.deb
          sudo dpkg -i drawio-amd64-26.2.2.deb

      # Step 3: Create output directories
      - name: Create output folders
        run: |
          mkdir -p svg_files html_files

      # Step 4: Convert .drawio files to SVG and wrap them in HTML
      - name: Convert Draw.io files
        run: |
          for file in $(find . -type f -name "*.drawio"); do
            base=$(basename "$file" .drawio)
            echo "Processing $base.drawio..."

            # Export to SVG
            draw.io --export --format svg --output "svg_files/${base}.svg" "$file"

            # Create an HTML wrapper
            echo '<!DOCTYPE html>' > "html_files/${base}.html"
            echo '<html lang="en">' >> "html_files/${base}.html"
            echo '<head>' >> "html_files/${base}.html"
            echo '  <meta charset="UTF-8">' >> "html_files/${base}.html"
            echo "  <title>${base}</title>" >> "html_files/${base}.html"
            echo '  <style>' >> "html_files/${base}.html"
            echo '    body { margin: 0; padding: 0; }' >> "html_files/${base}.html"
            echo '    svg { max-width: 100%; height: auto; display: block; }' >> "html_files/${base}.html"
            echo '  </style>' >> "html_files/${base}.html"
            echo '</head>' >> "html_files/${base}.html"
            echo '<body>' >> "html_files/${base}.html"

            cat "svg_files/${base}.svg" >> "html_files/${base}.html"

            echo '</body>' >> "html_files/${base}.html"
            echo '</html>' >> "html_files/${base}.html"

            # Log the changes
            echo "$(date) - Converted ${base}.drawio to SVG" >> svg_files/CHANGELOG.txt
            echo "$(date) - Wrapped ${base}.svg to HTML" >> html_files/CHANGELOG.txt
          done

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add svg_files html_files
          git diff-index --quiet HEAD || git commit -m "Auto-converted draw.io files"
          git push
