name: Convert Draw.io Files

on:
  push:
    paths:
      - '**/*.drawio'

# Add permissions needed for the workflow
permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository with history to detect changes
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to properly identify changed files

      # Step 2: Install dependencies
      - name: Install Draw.io and dependencies
        run: |
          sudo apt-get update
          # Use libasound2t64 instead of libasound2 for Ubuntu Noble (24.04)
          sudo apt-get install -y wget unzip xvfb libasound2t64 libgbm1 libnspr4 libnss3 libxss1
          wget https://github.com/jgraph/drawio-desktop/releases/download/v26.2.2/drawio-amd64-26.2.2.deb
          sudo apt-get -f install -y
          sudo dpkg -i drawio-amd64-26.2.2.deb || sudo apt-get -f install -y

      # Step 3: Create output directories
      - name: Create output folders
        run: |
          mkdir -p svg_files html_files
          
          # Initialize CSV changelogs with headers if they don't exist
          if [ ! -f "svg_files/CHANGELOG.csv" ]; then
            echo "Date,Time,User,Action,File,Type" > svg_files/CHANGELOG.csv
          fi
          if [ ! -f "html_files/CHANGELOG.csv" ]; then
            echo "Date,Time,User,Action,File,Type" > html_files/CHANGELOG.csv
          fi

      # Step 4: Convert .drawio files to SVG and wrap them in HTML
      - name: Convert Draw.io files
        run: |
          # Set up virtual display for headless operation
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          sleep 1 # Give Xvfb time to start

          # Use a different approach - temporary script
          cat > /tmp/convert-drawio.sh << 'EOL'
          #!/bin/bash
          input_file=$1
          output_file=$2
          drawio -x -f svg -o "$output_file" "$input_file"
          EOL
          chmod +x /tmp/convert-drawio.sh

          # Get the list of changed .drawio files in this commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep "\.drawio$" || echo "")
          echo "Changed files in this commit: $CHANGED_FILES"
          
          # Find all .drawio files and process them
          find . -type f -name "*.drawio" -print0 | while IFS= read -r -d $'\0' file; do
            # Get the base filename without extension, preserving spaces
            base=$(basename "$file" .drawio)
            
            # Check if this file was changed in the current commit
            if echo "$CHANGED_FILES" | grep -q "$file"; then
              echo "Processing changed file: $file"
              FILE_CHANGED=true
            else
              echo "Processing file (no changes): $file"
              FILE_CHANGED=false
            fi

            mkdir -p "svg_files"
            output_path="svg_files/${base}.svg"
            
            # Run the conversion with xvfb-run - quote variables to handle spaces properly
            xvfb-run -a /tmp/convert-drawio.sh "$file" "$output_path"
            
            # Check if conversion succeeded
            if [ ! -f "$output_path" ]; then
              echo "Failed to convert $file to SVG. Trying alternative method..."
              # Alternative approach using node directly if installed with drawio
              xvfb-run -a drawio -x -f svg -o "$output_path" "$file"
            fi

            # Create an HTML wrapper
            echo '<!DOCTYPE html>' > "html_files/${base}.html"
            echo '<html lang="en">' >> "html_files/${base}.html"
            echo '<head>' >> "html_files/${base}.html"
            echo '  <meta charset="UTF-8">' >> "html_files/${base}.html"
            echo "  <title>${base}</title>" >> "html_files/${base}.html"
            echo '  <style>' >> "html_files/${base}.html"
            echo '    body { margin: 0; padding: 0; }' >> "html_files/${base}.html"
            echo '    svg { max-width: 100%; height: auto; display: block; }' >> "html_files/${base}.html"
            echo '  </style>' >> "html_files/${base}.html"
            echo '</head>' >> "html_files/${base}.html"
            echo '<body>' >> "html_files/${base}.html"

            cat "svg_files/${base}.svg" >> "html_files/${base}.html"

            echo '</body>' >> "html_files/${base}.html"
            echo '</html>' >> "html_files/${base}.html"

            # Only log the changes if this file was modified in this commit
            if [ "$FILE_CHANGED" = true ]; then
              # Log the changes in CSV format with date as dd.mm.yyyy and full name
              # Get the full name of the author (or committer) of the latest commit that modified this file
              AUTHOR=$(git log -1 --format="%aN" -- "$file" || echo "${{ github.actor }}")
              FORMATTED_DATE=$(date +"%d.%m.%Y")
              FORMATTED_TIME=$(date +"%H:%M:%S")
              
              # Check if SVG already exists BEFORE we converted it to determine if this is a new diagram
              # We need to check git history to properly determine if the file is new or modified
              if git ls-files --error-unmatch "svg_files/${base}.svg" &>/dev/null; then
                CHANGE_TYPE="Modified"
              else
                CHANGE_TYPE="New"
              fi
              
              echo "$FORMATTED_DATE,$FORMATTED_TIME,\"$AUTHOR\",Converted,\"${base}.drawio\",\"$CHANGE_TYPE\"" >> svg_files/CHANGELOG.csv
              echo "$FORMATTED_DATE,$FORMATTED_TIME,\"$AUTHOR\",Wrapped to HTML,\"${base}.svg\",\"$CHANGE_TYPE\"" >> html_files/CHANGELOG.csv
              echo "Added entries to changelog for $file ($CHANGE_TYPE)"
            fi
          done

      # Step 5: Commit and push changes
      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add svg_files html_files
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Auto-converted draw.io files"
            # Use GitHub token for authentication
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi
