name: Export Drawio to HTML

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  export-drawio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for changelog purposes

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install draw.io-export
        run: npm install -g @drawio/export-cli

      - name: Create html_files directory if it doesn't exist
        run: mkdir -p html_files

      - name: Get changed .drawio files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.drawio$' | xargs)"

      - name: Export .drawio files to HTML
        run: |
          # Initialize an array to store new files
          new_files=()
          
          # Process each changed .drawio file
          for file in ${{ steps.changed-files.outputs.files }}; do
            echo "Processing $file"
            filename=$(basename "$file" .drawio)
            output_file="html_files/${filename}.html"
            
            # Check if this is a new file
            if [ ! -f "$output_file" ]; then
              new_files+=("$filename.html (new)")
            else
              new_files+=("$filename.html (updated)")
            fi
            
            # Export the diagram to HTML
            npx drawio-export --format html --output "$output_file" "$file"
            echo "Exported $file to $output_file"
          done
          
          # Store new files list for changelog
          echo "${new_files[@]}" > new_files_temp.txt

      - name: Update Changelog
        run: |
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          commit_hash="${{ github.sha }}"
          commit_msg=$(git log -1 --pretty=%B)
          new_files=$(cat new_files_temp.txt)
          
          if [ ! -f changelog.md ]; then
            echo "# Diagram Change Log" > changelog.md
            echo "" >> changelog.md
          fi
          
          {
            echo "## $timestamp"
            echo "- Commit: ${commit_hash}"
            echo "- Message: ${commit_msg}"
            echo "- Files:"
            for file in ${{ steps.changed-files.outputs.files }}; do
              echo "  - $file"
            done
            echo "- Exported HTML Files:"
            for file in ${new_files}; do
              echo "  - $file"
            done
            echo ""
          } > temp_changelog.md
          
          cat temp_changelog.md changelog.md > new_changelog.md
          mv new_changelog.md changelog.md
          rm temp_changelog.md new_files_temp.txt
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add html_files/ changelog.md
          git commit -m "Auto-export .drawio files to HTML and update changelog" || echo "No changes to commit"
          git push
